
# Netlify configuration file

# This redirects all routes to index.html, which is needed for single-page applications
# that use client-side routing (like React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Run build with CI=true to ensure tests don't hang and exit on failure
[build]
  command = "CI=true npm run test && npm run build"

# Specify the build directory
  publish = "dist"

# Environment variables (can be overridden in Netlify dashboard)
[build.environment]
  NODE_VERSION = "18"

# Optional: Custom headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
