
# Netlify configuration file

# This redirects all routes to index.html, which is needed for single-page applications
# that use client-side routing (like React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Updated build command to skip tests
[build]
  command = "npm run build && npm run test"
  publish = "dist"
  ignore_warnings = true

# Optional: Custom headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
