
# Netlify configuration file

# This redirects all routes to index.html, which is needed for single-page applications
# that use client-side routing (like React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Use a safer build command that checks if the test script exists before running it
[build]
  command = "npm run build"
  publish = "dist"

# Optional: Custom headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
