
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables with fallback values for local development
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://svuritdhlgaonfefphkz.supabase.co";
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2dXJpdGRobGdhb25mZWZwaGt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzMzIxOTQsImV4cCI6MjA1NjkwODE5NH0.vJ7t3i8QEA0pJLPG5j78u4qOt4eF_KoNC8_VOx_OoMo";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Define interfaces for the new tables to help with TypeScript
export interface FuelSettings {
  id: string;
  fuel_type: string;
  current_price: number;
  tank_capacity: number;
  current_level: number;
  updated_at?: string;
}

export interface DailyReading {
  id: string;
  date: string;
  fuel_type: string;
  dip_reading: number;
  opening_stock: number;
  receipt_quantity: number;
  closing_stock: number;
  sales_per_tank_stock?: number;
  actual_meter_sales: number;
  stock_variation?: number;
  created_at?: string;
}

// Enhance fuel test interface to include the new column
export interface FuelTest {
  id: string;
  fuel_type: 'Petrol' | 'Diesel';
  test_date: string;
  test_time: string;
  temperature: number;
  density: number;
  appearance: string;
  litres_tested: number;
  notes: string;
  tested_by: string;
  created_at: string;
  tested_by_name?: string;
}
