
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables with fallback values for local development
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://svuritdhlgaonfefphkz.supabase.co";
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2dXJpdGRobGdhb25mZWZwaGt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzMzIxOTQsImV4cCI6MjA1NjkwODE5NH0.vJ7t3i8QEA0pJLPG5j78u4qOt4eF_KoNC8_VOx_OoMo";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Define interfaces for the new tables to help with TypeScript
export interface FuelSettings {
  id: string;
  fuel_type: string;
  current_price: number;
  tank_capacity: number;
  current_level: number;
  updated_at?: string;
}

export interface DailyReading {
  id: string;
  date: string;
  fuel_type: string;
  dip_reading: number;
  opening_stock: number;
  receipt_quantity: number;
  closing_stock: number;
  sales_per_tank_stock?: number;
  actual_meter_sales: number;
  stock_variation?: number;
  created_at?: string;
}

export interface PumpSettings {
  id?: string;
  pump_number: string;
  nozzle_count: number;
  fuel_types: string[];
  created_at?: string;
}

export interface BusinessSettings {
  id?: string;
  gst_number: string;
  business_name: string;
  address: string;
  updated_at?: string;
}

export interface Reading {
  id: string;
  shift_id: string;
  staff_id: string;
  pump_id: string;
  date: string;
  opening_reading: number;
  closing_reading: number | null;
  cash_given: number;
  cash_remaining: number | null;
  card_sales: number | null;
  upi_sales: number | null;
  cash_sales: number | null;
  created_at?: string;
}

export interface FuelTest {
  id: string;
  fuel_type: 'Petrol' | 'Diesel';
  test_date: string;
  test_time: string;
  temperature: number;
  density: number;
  appearance: string;
  litres_tested: number;
  notes: string;
  tested_by: string;
  created_at: string;
  tested_by_name?: string;
}

export interface Customer {
  id: string;
  name: string;
  contact: string;
  phone: string;
  email: string;
  gst: string;
  balance: number | null;
  created_at?: string;
}

export interface Vehicle {
  id: string;
  customer_id: string;
  number: string;
  type: string;
  capacity: string;
  created_at?: string;
}

export interface Indent {
  id: string;
  customer_id: string;
  vehicle_id: string;
  fuel_type: string;
  amount: number;
  quantity: number;
  status: string | null;
  created_at?: string;
}

export interface Transaction {
  id: string;
  customer_id: string | null;
  vehicle_id: string | null;
  staff_id: string;
  date: string;
  fuel_type: string;
  amount: number;
  quantity: number;
  payment_method: string;
  indent_id: string | null;
  created_at?: string;
}
